# Site settings
title: pandorabots
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

exclude:
  - "bower_components"
  - "bower.json"

collections:
  aiml:
    output: true
    permalink: /aiml/:path/
  deployments:
    output: true
    permalink: /deployments/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  integrations:
    output: true
    permalink: /integrations/:path/
  articles:
    output: true
    permalink: /articles/:path/
  modules:
    output: true
    permalink: /modules/:path/
